import { McpHub } from "../src/main/control/mcp-hub";
import * as path from "path";

async function verifyMcpFlow() {
  console.log("Starting MCP Verification...");

  const mcpHub = new McpHub();

  // Path to the built server file (using the one generated by electron-vite build)
  const serverPath = path.resolve(__dirname, "../out/main/desktop-mcp.js");

  console.log(`Target Server Path: ${serverPath}`);

  try {
    // 1. Connect
    console.log("1. Connecting to Desktop MCP Server...");
    await mcpHub.connectToServer({
      id: "test-desktop",
      name: "Test Desktop Automation",
      command: "node", // We run with node directly
      args: [serverPath],
      env: {
        ...process.env,
        ELECTRON_RUN_AS_NODE: "1",
      },
    });
    console.log("✅ Connected.");

    // 2. List Tools
    console.log("2. Listing Tools...");
    const tools = await mcpHub.getAllTools();
    console.log(
      "Available Tools:",
      tools.map((t: any) => t.name),
    );

    if (tools.length === 0) {
      throw new Error("No tools found!");
    }
    console.log("✅ Tools listed.");

    // 3. Call Tool (get_active_window_tree)
    console.log("3. Calling tool: get_active_window_tree...");
    // Use depth 1 to keep it fast and output small
    const result = await mcpHub.callTool(
      "test-desktop",
      "get_active_window_tree",
      { depth: 1 },
    );

    // Parse result content to verify it's JSON
    const content = result.content[0];
    if (content.type === "text") {
      const tree = JSON.parse(content.text);
      console.log("Result Root Name:", tree.Name || "Unknown");
      console.log(
        "Result ControlType:",
        tree.LocalizedControlType || "Unknown",
      );
    }
    console.log("✅ Tool call successful.");

    // 4. Call Tool (get_screenshot)
    console.log("4. Calling tool: get_screenshot...");
    const screenshotResult = await mcpHub.callTool(
      "test-desktop",
      "get_screenshot",
      {},
    );
    const screenshotContent = screenshotResult.content[0];
    if (screenshotContent.type === "image") {
      console.log(
        "Screenshot captured. Data length:",
        screenshotContent.data.length,
      );
      if (screenshotContent.data.length < 100) {
        throw new Error("Screenshot data seems too small!");
      }
    } else {
      throw new Error("Screenshot tool returned non-image content!");
    }
    console.log("✅ Screenshot call successful.");

    process.exit(0);
  } catch (error) {
    console.error("❌ Verification Failed:", error);
    process.exit(1);
  }
}

verifyMcpFlow();
