/**
 * Z-One Workflow Engine — Type Definitions
 *
 * A DAG-based workflow model supporting task execution, conditional branching,
 * loops, and gateway (join) nodes.
 */

// ─── Node Types ───────────────────────────────────────────────────────────────

export type NodeType = "task" | "condition" | "loop" | "gateway";

export type NodeStatus =
  | "pending"
  | "waiting"
  | "running"
  | "completed"
  | "failed"
  | "skipped";

export type WorkflowStatus =
  | "draft"
  | "running"
  | "paused"
  | "completed"
  | "failed";

// ─── Node Configs ─────────────────────────────────────────────────────────────

export interface TaskConfig {
  /** Agent persona / system prompt for this task */
  agentPersona: string;
  /** Tool names the agent can use */
  tools: string[];
  /** Suggested tools the agent can optionally use (generated by planner) */
  suggestedTools?: string[];
  /** Task prompt template. Supports {{nodeId.output}} references. */
  prompt: string;
  /** Labels of privacy vault data this task requires */
  requiresPrivacy?: string[];
}

export interface ConditionConfig {
  /** Condition expression for LLM evaluation. Can reference {{nodeId.output}} */
  expression: string;
  /** Branches with labels mapping to edge IDs */
  branches: { label: string; edgeId: string }[];
}

export interface LoopConfig {
  /** Maximum number of iterations (0 = unlimited, use exitCondition) */
  maxIterations: number;
  /** Exit condition expression — loop stops when this evaluates to true */
  exitCondition: string;
  /** Interval between iterations in ms (for polling/monitoring tasks) */
  intervalMs?: number;
  /** IDs of nodes that form the loop body */
  bodyNodeIds: string[];
}

export interface GatewayConfig {
  /** 'all' = wait for all incoming branches, 'any' = proceed on first */
  mode: "all" | "any";
}

export type NodeConfig = TaskConfig | ConditionConfig | LoopConfig | GatewayConfig;

// ─── Workflow Definition ──────────────────────────────────────────────────────

export interface WorkflowNode {
  id: string;
  type: NodeType;
  label: string;
  config: NodeConfig;
  /** Position for UI rendering */
  position: { x: number; y: number };
}

export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  /** Condition label for condition node outgoing edges (e.g. "true", "false") */
  condition?: string;
}

export interface WorkflowDefinition {
  id: string;
  name: string;
  description: string;
  version: number;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  /** Device that created this workflow — results push back here */
  sourceDeviceId: string;
  /** Session that this workflow was created from */
  sourceSessionId: string;
  createdAt: number;
  updatedAt: number;
}

// ─── Runtime State ────────────────────────────────────────────────────────────

export interface NodeRun {
  nodeId: string;
  status: NodeStatus;
  output?: any;
  logs: string[];
  /** Number of iterations (for loop nodes) */
  iterations?: number;
  startedAt?: number;
  completedAt?: number;
  /** Messages injected by user — consumed by agent on next iteration */
  messageQueue: string[];
}

export interface WorkflowRun {
  id: string;
  workflowId: string;
  status: WorkflowStatus;
  /** Global context shared between nodes. Keys = nodeId, Values = node output */
  context: Record<string, any>;
  /** State of each node in this run */
  nodeStates: Record<string, NodeRun>;
  startedAt: number;
  completedAt?: number;
}

// ─── Version History ──────────────────────────────────────────────────────────

export interface WorkflowVersion {
  id: string;
  workflowId: string;
  version: number;
  definition: WorkflowDefinition;
  changelog: string;
  createdAt: number;
}

// ─── Events ───────────────────────────────────────────────────────────────────

export type WorkflowEventType =
  | "node:started"
  | "node:completed"
  | "node:failed"
  | "node:log"
  | "node:messageInjected"
  | "workflow:started"
  | "workflow:paused"
  | "workflow:resumed"
  | "workflow:completed"
  | "workflow:failed"
  | "workflow:versionUpdated";

export interface WorkflowEvent {
  type: WorkflowEventType;
  workflowId: string;
  runId: string;
  nodeId?: string;
  data?: any;
  timestamp: number;
}
